name: Publish i2pd to Docker HUB

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Clone i2pd
        run: |
            git clone https://github.com/PurpleI2P/i2pd.git
            echo "version=$(git -C ./i2pd describe --tags --abbrev=0)" >> $GITHUB_ENV
            ls
